./bin/FPartPassword: FPartPassword.cpp
	mkdir -p bin
	g++ -o bin/main FPartPassword.cpp

./bin/SPartPassword: SPartPassword.cpp
	mkdir -p bin
	g++ -o bin/main SPartPassword.cpp

test:
	./bin/main

clean:
	rm -rf bin